### ISSUE TITLE
.NET API browser: broken rendering of inheritance chain

### ISSUE THREAD

**Issue by pkulikov** [dotnet/dotnet-api-docs#3477] opened 2019-11-13 21:06 UTC
The inheritance chain renders in a hard to read way, for example, [ListView control API](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.listview?view=netcore-3.0):
![image](https://user-images.githubusercontent.com/15279990/68804286-ac44b600-0661-11ea-81d6-f78610df0dc9.png)

**Comment by mairaw** [comment] 2019-11-15 21:43
Thanks @pkulikov. Closing this as a duplicate of  https://github.com/MicrosoftDocs/feedback/issues/2064.

**Closed by mairaw** 2019-11-15 21:43 UTC
Labels: duplicate
