### ISSUE TITLE
Incorrect "Applies to" in overload of Remove

### ISSUE THREAD

**Issue by saltukkos** [dotnet/dotnet-api-docs#1237] opened 2018-11-29 16:15 UTC
public bool Remove (TKey key, out TValue value);
It's written, that this overload is present in NetFramework &gt;=2.0, in Net Standard etc., but It's a lie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7421c53-c788-32a3-4c47-19e802196efb
* Version Independent ID: cdde8107-dd1a-4a37-fad8-5ebe4cd67949
* Content: [Dictionary&lt;TKey,TValue&gt;.Remove Method (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=netcore-2.0#System_Collections_Generic_Dictionary_2_Remove__0__1__)
* Content Source: [xml/System.Collections.Generic/Dictionary`2.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/Dictionary`2.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by am11** [comment] 2019-01-20 10:16
Seems like we get a union of supported platforms by all APIs listed on a page. Would probably make sense if `Applies to` is under each API instead of once per page:

Reading in this view:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=netcore-2.0, it is unclear that:

`public bool Remove (TKey key);` is supported for all platforms
but `public bool Remove (TKey key, out TValue value);` is only supported for .NET Core 2.0+.

**Comment by am11** [comment] 2019-01-20 10:17
Seems like we get a union of supported platforms by all APIs listed on a page. Would probably make sense if `Applies to` is under each API instead of once per page.

Reading in this view:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=netcore-2.0, it is unclear that:

`public bool Remove (TKey key);` is supported for all platforms
but `public bool Remove (TKey key, out TValue value);` is only supported for .NET Core 2.0+.

**Comment by svick** [comment] 2019-01-20 12:10
This looks like a duplicate of https://github.com/MicrosoftDocs/feedback/issues/314.

**Comment by mairaw** [comment] 2019-03-08 03:55
It is @svick. Closing this one.

Right now the best way to see if the API is supported or not on the target you want is to select the desired version and look at the list of overloads. That should be correct.

**Closed by mairaw** 2019-03-08 03:55 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
