### ISSUE TITLE
Documentation missing for latest iOS platform libraries

### ISSUE THREAD

**Issue by tuanchien** [dotnet/dotnet-api-docs#10178] opened 2024-07-30 01:35 UTC
### Describe the issue or suggestion

The only version of the iOS platform library APIs that appears to be published on the Microsoft website are for Xamarin iOS SDK 12.

The current net8.0 SDK seems to have platform support iOS and MacCatalyst 17.0 features.

It would be great to have updated documentation for the current libraries.

**Comment by jeremy-visionaid** [comment] 2024-07-30 01:37
Likewise, the API browser only shows .NET for Android

**Comment by Jozkee** [comment] 2024-07-31 21:21
cc @davidbritch @gewarren

**Comment by Jozkee** [comment] 2024-07-31 21:27
@tuanchien @jeremy-visionaid aren't you looking for https://learn.microsoft.com/en-us/dotnet/api/?view=net-maui-8.0?

**Comment by jeremy-visionaid** [comment] 2024-07-31 21:32
@Jozkee I'm looking for documentation for https://github.com/xamarin/xamarin-macios - i.e. for Native C# iOS apps, not MAUI.

The nearest I can find is here:
https://learn.microsoft.com/en-us/dotnet/api/?view=xamarin-ios-sdk-12

But that's for version 12, and Xamarin is obsolete. The latest projections are for SDK version 17 and are in Microsoft.iOS, not Xamarin.iOS

**Comment by jeremy-visionaid** [comment] 2024-07-31 21:36
@Jozkee IIRC the newer projections for Microsoft.iOS were available in the API browser - I believe their absence is a regression

**Comment by gewarren** [comment] 2024-08-14 03:48
@davidbritch Can you take a look?

**Comment by jeremy-visionaid** [comment] 2024-12-02 20:26
Well, it's been nearly half a year, and the iOS/Catalyst binding documentation is still missing. So, bump!

**Comment by jeremy-visionaid** [comment] 2024-12-02 20:31
I'm guessing that this depends on https://github.com/xamarin/xamarin-macios/issues/14372

**Comment by gewarren** [comment] 2024-12-04 00:58
I'm going to close this issue in favor of https://github.com/xamarin/xamarin-macios/issues/14372 since those docs wouldn't be published out of this repo.

**Closed by gewarren** 2024-12-04 00:58 UTC
Labels: untriaged, Pri3, needs-area-label
