### ISSUE TITLE
Question: SearchResultEntry return type of SearchResultEntry.Attributes 

### ISSUE THREAD

**Issue by surfmuggle** [dotnet/dotnet-api-docs#8779] opened 2023-01-11 18:25 UTC
The docs for [SearchResultEntry.Attributes](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.searchresultentry.attributes?view=dotnet-plat-ext-7.0) state

> The Attributes property contains a collection of DirectoryAttribute objects.

But this seems not to be the case:

```cs
SearchResponse response = (SearchResponse) ldapConnection.SendRequest(GetSearch());
WriteItemEntry(response.Entries);

private static void WriteItemEntry(SearchResultEntryCollection entries)
{
    foreach (var item in entries[0].Attributes) 
    {                                
        if(item.GetType() == typeof(System.Collections.DictionaryEntry))
        {
            Console.WriteLine("item is of type System.Collections.DictionaryEntry");
        }    
    }
}  
```
The above returns true for every item in SearchResultEntryCollection[0].Attributes. Therefore to my understanding the documentation should state 

> Attributes property contains a collection of DictionaryEntry objects

Is this assumption correct?

**Comment by buyaa-n** [comment] 2023-01-19 00:27
From the [source](https://referencesource.microsoft.com/#System.DirectoryServices.Protocols/System/DirectoryServices/Protocols/SearchResultEntry.cs)`SearchResultEntry.Attributes` type is [SearchResultAttributeCollection](https://learn.microsoft.com/en-us/dotnet/api/system.directoryservices.protocols.searchresultattributecollection) which is documented as: 

> `SearchResultAttributeCollection` class is a collection of `DirectoryAttribute` objects.

And the source of [SearchResultAttributeCollection](https://referencesource.microsoft.com/#System.DirectoryServices.Protocols/System/DirectoryServices/Protocols/SearchResultEntry.cs) it does contain collection of DirectoryAttribute:
```cs
namespace System.DirectoryServices.Protocols
{
    [DefaultMember("Item")]
    public class SearchResultAttributeCollection : DictionaryBase
    {
        public DirectoryAttribute this[string attributeName] { get; }
 
        public ICollection AttributeNames { get; }
        public ICollection Values { get; }
 
        public bool Contains(string attributeName);
        public void CopyTo(DirectoryAttribute[] array, int index);
    }
}
```

The `DictionaryEntry` you are seeing is coming from Enumeration result of foreach loop, so closing by design

**Closed by buyaa-n** 2023-01-19 00:27 UTC
Labels: untriaged, Pri3, area-System.DirectoryServices
