### ISSUE TITLE
source link in docs #doc-enhancement 

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/dotnet-api-docs#3209] opened 2019-09-18 18:33 UTC
Hi!

I do not see in the documentation a link to the source code for the implementation of what is described on the current page.

First of all, I'm interested in net core.

I can not imagine how much effort this will take and what is the least costly solution.

Thank you.

**Comment by mairaw** [comment] 2019-09-18 18:47
Thanks for your feedback @lobster2012-user. This is a duplicate of https://github.com/MicrosoftDocs/feedback/issues/433.

For now, the easiest way is to browse the .NET Core source code using https://source.dot.net/.

**Closed by mairaw** 2019-09-18 18:47 UTC
Labels: docs-experience, external

**Comment by gewarren** [comment] 2024-04-04 17:23
Great news - the core .NET libraries now have links to source code!
Example: https://learn.microsoft.com/dotnet/api/system.string.chars?view=net-8.0
