### ISSUE TITLE
A few JsonObject methods are listed as being available in .NET 8, but in reality they aren't

### ISSUE THREAD

**Issue by Bellarmine-Head** [dotnet/dotnet-api-docs#10501] opened 2024-10-06 08:30 UTC
### Type of issue

Other (describe below)

### Description

[Enter feedback here]
The documentation for `JsonObject` methods `GetAt`, `IndexOf`, `SetAt`, `RemoveAt`, `Insert` say that they are available in .NET 8.  

E.g. https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonobject.indexof?view=net-8.0

This is annoying, because I looked for them in vain, and thought I was getting something wrong.

But in fact, these methods are being added in .NET 9 and are not available in any previous version.

See https://github.com/dotnet/runtime/issues/102932

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonobject.indexof?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text.Json.Nodes/JsonObject.xml

### Document Version Independent Id

75219c28-7f0a-b336-60ff-09fbe63729a2

### Article author

@dotnet-bot

**Comment by Bellarmine-Head** [comment] 2024-10-06 08:32
![image](https://github.com/user-attachments/assets/a3b1a124-5e2c-4f9d-9a4f-ca7e596611fb)

**Comment by berezovskyi** [comment] 2024-10-11 09:07
same for https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.deepequals?view=net-8.0#system-text-json-jsonelement-deepequals(system-text-json-jsonelement-system-text-json-jsonelement)

**Comment by gewarren** [comment] 2024-10-19 00:30
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is they the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:30 UTC
Labels: untriaged, Pri3, area-System.Text.Json
