### ISSUE TITLE
Methods name in navigation pane should not be translated

### ISSUE THREAD

**Issue by ImmobilisCommander** [dotnet/dotnet-api-docs#9908] opened 2024-05-14 10:18 UTC
Method names are translated and should not be

![image](https://github.com/dotnet/dotnet-api-docs/assets/64332874/9ed1d2c7-af7c-45cc-a1ac-e5bcdb894fa3)

https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.generic.list-1.remove?view=net-8.0

**Comment by gewarren** [comment] 2024-05-15 00:31
Thanks - we're aware of the problem and apparently there's no easy fix :( Closing as a dupe of #8814. cc @kgliang

**Closed by gewarren** 2024-05-15 00:31 UTC
Labels: loc, untriaged, Pri3, needs-area-label
