### ISSUE TITLE
TcpChannel Class Example Error

### ISSUE THREAD

**Issue by MaxFun** [dotnet/dotnet-api-docs#10317] opened 2024-08-25 13:50 UTC
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
VS 2022, created an empty project(.NET Framework) .NETFramework 4.8.1 and pasted example server code from webpage. It has many errors, even "using System.Runtime.Remoting.Channels.Tcp;" produces an error.
Need to know how to fix and the IDE should be listed that the example worked with.
[TestServer.zip](https://github.com/user-attachments/files/16740469/TestServer.zip)

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.remoting.channels.tcp.tcpchannel?view=netframework-4.8.1&viewFallbackFrom=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.Remoting.Channels.Tcp/TcpChannel.xml

### Document Version Independent Id

be2b05de-e3ef-5732-416d-624b057189f9

### Article author

@dotnet-bot

**Comment by MaxFun** [comment] 2024-08-25 13:54
Need to fix dotnet-bot or stop using it. Its really dumb

**Comment by rzikm** [comment] 2024-08-26 08:53
duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10314

**Closed by rzikm** 2024-08-26 08:53 UTC
Labels: untriaged, Pri3, needs-area-label
