### ISSUE TITLE
System.IO.DirectoryInfo is missing some properties

### ISSUE THREAD

**Issue by samyun** [dotnet/dotnet-api-docs#4118] opened 2020-04-16 18:20 UTC
See https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo?view=netcore-3.1

On the left sidebar, under DirectoryInfo->Properties, for .NET Core 3.1, only "Exists", "Name", "Parent", and "Root" are listed. However, I would expect "FullName" to also be available, but the docs say it's only applicable to .NET Framework 4.8, 4.72, 4.71, 4.7. https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.fullname?view=netframework-4.8&viewFallbackFrom=netcore-3.1#System_IO_DirectoryInfo_FullName

**Comment by TianqiZhang** [comment] 2020-05-26 02:09
@samyun the docs is correct, `FullName` is only defined in `DirectoryInfo` class for .NET Framework 4.7, 4.71, 4.72 and 4.8.

In .NET Core, `FullName` is defined in `FileSystemInfo` and inherited by `DirectoryInfo`, as mentioned here:
![image](https://user-images.githubusercontent.com/5326582/82853549-a7c65780-9f38-11ea-86dd-2cd46c8d5a55.png)

On the left side TOC, we only show what's defined in this class, that's why you can't find `FullName` in it under .NET Core. However if you switch to .NET Framework 4.8 for example, you'll see `FullName` listed there:
![image](https://user-images.githubusercontent.com/5326582/82853664-e8be6c00-9f38-11ea-8fa4-f3f57d8115dd.png)

**Comment by gewarren** [comment] 2020-05-26 17:37
Closing this issue since it's "by design" that the properties don't appear in the table of contents.

**Closed by gewarren** 2020-05-26 17:37 UTC
Labels: :watch: Not Triaged
