### ISSUE TITLE
StartInfo's Attribution

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2210] opened 2019-03-28 18:51 UTC
@infinitylight commented on [Thu Mar 28 2019](https://github.com/dotnet/dotnet-api-docs.zh-cn/issues/22)

[在此处输入反馈]

Maybe the "public System.Diagnostics.ProcessStartInfo StartInfo { get; set; }" should be 
"public System.Diagnostics.Process.StartInfo{ get; set; }".
If the "public System.Diagnostics.ProcessStartInfo StartInfo { get; set; }" is right is meaning the 
StartInfo belongs both Process Class and ProcessStartInfo Class!
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 61b333a8-bdf9-4222-41d1-e9044cc92b66
* Version Independent ID: 9e3d7bfa-b873-f155-6a54-8e9877a8dc2a
* Content: [Process.StartInfo Property (System.Diagnostics)](https://docs.microsoft.com/zh-cn/dotnet/api/system.diagnostics.process.startinfo?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.Diagnostics/Process.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.Diagnostics/Process.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

---

@imba-tjd commented on [Thu Mar 28 2019](https://github.com/dotnet/dotnet-api-docs.zh-cn/issues/22#issuecomment-477483204)

There is no error. It's auto generated from source code.

**Comment by CeciAc** [comment] 2019-03-28 18:52
Hi team, 
The user suggested it may be an error on the code
best

**Comment by mairaw** [comment] 2019-03-29 22:22
That is correct. That's the actual type of that property:
![image](https://user-images.githubusercontent.com/12971179/55265606-49b7ba80-5236-11e9-8f97-b58f04c9b657.png)

https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Process.cs,b0417e5300dc5565

So closing by design.

**Closed by mairaw** 2019-03-29 22:22 UTC
Labels: :watch: Not Triaged, Source - Docs.ms

**Comment by infinitylight** [comment] 2019-03-30 03:13
Thank you so very much!
And I wanna introduce it by my style.
Would you like to have a look  and show me something that could be  help me make it completely？
Maybe the StartInfo belongs to Process Class is because for it's ProcessStartInfo's   instance  in Process Class.
In Process:
33        DefaultProperty("StartInfo"),
77       ProcessStartInfo startInfo;

 public ProcessStartInfo StartInfo {
            get {
                if (startInfo == null) {
                    startInfo = new ProcessStartInfo(this);
                }                
                return startInfo;
            }


In ProcessStartInfo.cs :
  public ProcessStartInfo() {
        } 
        internal ProcessStartInfo(Process parent) {
            this.weakParentProcess = new WeakReference(parent);
        }

        /// <devdoc>
        ///     Specifies the name of the application or document that is to be started.
        /// </devdoc>
        [ResourceExposure(ResourceScope.Machine)]
        public ProcessStartInfo(string fileName) {
            this.fileName = fileName;
        }
 
        /// <devdoc>
        ///     Specifies the name of the application that is to be started, as well as a set
        ///     of command line arguments to pass to the application.
        /// </devdoc>
        [ResourceExposure(ResourceScope.Machine)]
        public ProcessStartInfo(string fileName, string arguments) {
            this.fileName = fileName;
            this.arguments = arguments;
        }
