### ISSUE TITLE
No specification of options values

### ISSUE THREAD

**Issue by kwalker360** [dotnet/dotnet-api-docs#1914] opened 2019-02-21 01:09 UTC
On the page for the Microsoft.Win32.FileDialog.Options property, there is discussion that the property's value is a set of flags. But there is no description of (or link to a description of) what the flag values are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6679230f-3176-9367-ffae-7aab2200bd7e
* Version Independent ID: 679bbd1a-ec5f-ef73-b2e9-a1bb4e935ae5
* Content: [FileDialog.Options Property (Microsoft.Win32)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.filedialog.options?view=netframework-4.6.1#Microsoft_Win32_FileDialog_Options)
* Content Source: [xml/Microsoft.Win32/FileDialog.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.Win32/FileDialog.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment] 2019-04-15 23:34
Thanks for you feedback , @kwalker360. As the documentation notes:

> The actual options are exposed as properties on the specific dialogs, but not documented as public flag values at this level, so the uses of this property are mainly internal, for use when implementing the derived classes OpenFileDialog and SaveFileDialog.

Since the FileDialog.Options property is intended for internal use, we haven't provided detailed documentation on individual flags.

Closing as By Design.

**Closed by rpetrusha** 2019-04-15 23:34 UTC
Labels: Source - Docs.ms, by-design
