### ISSUE TITLE
Misleading information about JsonStringEnumMemberNameAttribute availability

### ISSUE THREAD

**Issue by manison** [dotnet/dotnet-api-docs#10524] opened 2024-10-09 14:01 UTC
### Type of issue

Missing information

### Description

Both version selector combo box and Applies To table indicates that the `JsonStringEnumMemberNameAttribute` is available in .NET 8 and above. The attribute has been introduced in .NET 9 preview 6 however.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonstringenummembernameattribute?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text.Json.Serialization/JsonStringEnumMemberNameAttribute.xml

### Document Version Independent Id

262fd87c-bc8d-335b-246e-271135dadca7

### Article author

@dotnet-bot

**Comment by gewarren** [comment] 2024-10-19 00:30
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is they the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:30 UTC
Labels: doc-bug, Pri3, area-System.Text.Json
