### ISSUE TITLE
Activity.AddLink method is listed as supported in .NET 8, but it's only available since .net 9

### ISSUE THREAD

**Issue by lmolkova** [dotnet/dotnet-api-docs#10478] opened 2024-10-01 15:47 UTC
### Type of issue

Typo

### Description

See Activity code for .NET 8 https://github.com/dotnet/runtime/blob/v8.0.8/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs

`AddLink` is not there yet.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activitylink?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics/ActivityLink.xml

### Document Version Independent Id

b3635974-59d7-651d-212a-d75a32e6297b

### Article author

@dotnet-bot

**Comment by gewarren** [comment] 2024-10-19 00:29
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is they the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:29 UTC
Labels: untriaged, Pri3, area-System.Diagnostics
