### ISSUE TITLE
Channel<string>  Reader.TryRead expects string? not string.

### ISSUE THREAD

**Issue by norlesh** [dotnet/dotnet-api-docs#10335] opened 2024-08-29 07:40 UTC
### Type of issue

Missing information

### Description

Documentation says the signature for a specific type T is TryRead(out T item) yet Visual Studio shows squiggles for TryRead(out string item) until I change it to TryRead(out string? item) ... either the program or the documentation is on the fritz.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.tryread?view=net-8.0#system-threading-channels-channelreader-1-tryread(-0@)

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Threading.Channels/ChannelReader`1.xml

### Document Version Independent Id

e119a925-5e42-10fb-d5d4-831dd92b12ba

### Article author

@dotnet-bot

**Comment by krwq** [comment] 2024-09-03 15:57
In the [code](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Threading.Channels/src/System/Threading/Channels/ChannelReader.cs#L36) and [ref](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Threading.Channels/ref/System.Threading.Channels.cs#L54):

it's annotated as `public abstract bool TryRead([MaybeNullWhen(false)] out T item)`.

So until you do i.e.:

`if (channel.TryRead(... out string? foo))` it will produce warnings but inside of `if` statement compiler will know that `foo` is not null so you will not get a warning when doing i.e.:

```csharp
`if (channel.TryRead(... out string? foo))
{
  string bar = foo;
  // ...
}
```

**Comment by krwq** [comment] 2024-09-03 15:59
Closing since it seems by design - please reopen or create a new issue if you have any extra questions.

**Closed by krwq** 2024-09-03 15:59 UTC
Labels: untriaged, Pri3, needs-area-label
