### ISSUE TITLE
pipeServer.ReadMode assignment error

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2650] opened 2019-06-27 17:10 UTC
@ummpython commented on [Thu Jun 27 2019](https://github.com/dotnet/dotnet-api-docs.zh-cn/issues/37)

Anonymous pipe pipeServer.ReadMode does not support PipeTransmissionMode.Message

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 4d376d7d-5bb0-d010-4584-b26913b9aa8c
* Version Independent ID: 58a4e996-64f1-9a4b-c334-34ae523dc029
* Content: [AnonymousPipeServerStream Class (System.IO.Pipes)](https://docs.microsoft.com/zh-cn/dotnet/api/system.io.pipes.anonymouspipeserverstream?view=netframework-4.5.2)
* Content Source: [xml/System.IO.Pipes/AnonymousPipeServerStream.xml](https://github.com/dotnet/dotnet-api-docs.zh-cn/blob/live/xml/System.IO.Pipes/AnonymousPipeServerStream.xml)
* Product: **dotnet-api**
* Technology: **system.io**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment] 2019-06-27 17:12
Hi team
I moved this here because it looks like the user is refering to an original instruction
best regards

**Comment by rpetrusha** [comment] 2019-06-28 17:18
Thanks, @CeciAc, for moving this issue.  Although setting the ReadMode property to an unsupported value was done by design, it made no sense to do that. We've modified the example in dotnet/samples#1038.

**Closed** 2019-07-01 16:56 UTC
Labels: :file_folder: Repo - dotnet-api-docs, :file_folder: Repo - samples, Source - Docs.ms
