### ISSUE TITLE
Gauge<T> class is not part of .NET 8

### ISSUE THREAD

**Issue by epenelle-genetec** [dotnet/dotnet-api-docs#10579] opened 2024-10-17 14:38 UTC
### Type of issue

Wrong versions

### Description

The Gauge<T> class is not part of  .NET 8. From my understanding, it is only available in .NET9 

See PR here.
https://github.com/dotnet/runtime/commit/c5295800e9ec0b25f071a550f4901b0bec3e307d#diff-4cfab5d647aaab47f024b5c768bace33b3987493caa878583dfa101a70d48510R355

If I am wrong, please just kindly let me know for my personal understanding and to avoid false issue in the future. 

Thanks for your time,

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.gauge-1?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics.Metrics/Gauge`1.xml

### Document Version Independent Id

40be00e4-b2c4-2443-541c-dc6838a74666

### Article author

@dotnet-bot

**Comment by gewarren** [comment] 2024-10-19 00:31
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is why the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:31 UTC
Labels: untriaged, Pri3, area-System.Diagnostics
