### ISSUE TITLE
Add description

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#2062] opened 2019-03-21 16:11 UTC
@Beautyod commented on [Thu Mar 21 2019](https://github.com/dotnet/dotnet-api-docs.de-de/issues/18)

Please add a description for this method.

I wonder what happens when the key already exists.
Just nothing or will it throw an exception.
Such information is important for the users.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 81498c77-e953-d79b-d758-09e63edc61fd
* Version Independent ID: 51907d96-b483-143d-0462-45d3b3cd2b30
* Content: [Dictionary&lt;TKey,TValue&gt;.TryAdd(TKey, TValue) Method (System.Collections.Generic)](https://docs.microsoft.com/de-de/dotnet/api/system.collections.generic.dictionary-2.tryadd?view=netcore-2.2&viewFallbackFrom=netframework-4.6.2)
* Content Source: [xml/System.Collections.Generic/Dictionary`2.xml](https://github.com/dotnet/dotnet-api-docs.de-de/blob/live/xml/System.Collections.Generic/Dictionary`2.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment] 2019-03-21 16:15
Hi team, 
The contributor is making a suggestion on the original documentation
best

**Comment by mairaw** [comment] 2019-04-04 23:11
Closing as a duplicate of #939

**Closed by mairaw** 2019-04-04 23:11 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
