### ISSUE TITLE
Missing status enum value for 11050

### ISSUE THREAD

**Issue by Bunnywood** [dotnet/dotnet-api-docs#10580] opened 2024-10-17 16:52 UTC
### Type of issue

Typo

### Description

Im receiving a PingResult.Status value of 11050 which is not in the enum. It would be nice to know what it means.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.net.networkinformation.ipstatus?view=net-8.0&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(System.Net.NetworkInformation.IPStatus)%3Bk(DevLang-VB)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Net.NetworkInformation/IPStatus.xml

### Document Version Independent Id

365cbbc6-cdf9-af6a-6d80-595edf3633fb

### Article author

@karelz

**Comment by MihaZupan** [comment] 2024-10-17 17:00
Duplicate of https://github.com/dotnet/runtime/issues/101999

**Closed by MihaZupan** 2024-10-17 17:00 UTC
Labels: area-System.Net, untriaged, Pri3
