### ISSUE TITLE
FileSystemWatcher docs should describe the inotify limits

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/dotnet-api-docs#7625] opened 2022-01-24 08:30 UTC
The `FileSystemWatcher` users (including majority of ASP.NET Core users) are frequently getting an error similar to:

> The configured user limit ($ABC) on the number of inotify instances has been reached

The [remarks section](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0#remarks) of the `FileSystemWatcher` type should contain an explanation how to properly modify this limit, as it's not obvious that the settings stored in the "/proc/sys/fs/inotify/max_user_watches" file are not persisted (https://github.com/dotnet/runtime/pull/62096#issuecomment-981662587)

Related:

* https://stackoverflow.com/questions/43469400/asp-net-core-the-configured-user-limit-128-on-the-number-of-inotify-instance
* https://github.com/dotnet/runtime/pull/62096

**Comment by yecril71pl** [comment] 2022-01-24 15:48
> The [remarks section](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-6.0#remarks) of the `FileSystemWatcher` type should contain an explanation how to properly modify this limit, as it's not obvious that the settings stored in the "/proc/sys/fs/inotify/max_user_watches" file are not persisted ([dotnet/runtime#62096 (comment)](https://github.com/dotnet/runtime/pull/62096#issuecomment-981662587))

duplicate of #7409

**Closed** 2022-03-15 18:09 UTC
Labels: up-for-grabs, Pri3, area-System.IO, :watch: Not Triaged
