### ISSUE TITLE
OperationCanceledExceptions not documented for TcpListener

### ISSUE THREAD

**Issue by wischi-chr** [dotnet/dotnet-api-docs#7692] opened 2022-02-05 10:10 UTC
I just noticed that cancellable async methods like `AcceptTcpClientAsync(CancellationToken cancellationToken)` on the `TcpListener` don't have documented `OperationCanceledExceptions`. Is that on purpose because this exception is "implied" when a `CancellationToken` is passed in or is that missing?

**Comment by greenEkatherine** [comment] 2022-02-09 13:06
@antonfirsov could you please help with it?

**Comment by antonfirsov** [comment] 2022-02-09 13:45
The issue is not specific to `TcpListener`. We usually don't document `OperationCanceledException` for `Task`-based methods . The reason is that the exception is never thrown during the call to the method (eg. `AcceptTcpClientAsync`), but when the resulting `Task` is awaited, so strictly speaking, it doesn't belong to the method invocation.

In my opinion this is not ideal, because there is no way for users to prepare for the exceptions methods can throw asynchronously, but it would be a huge effort to change this across all our docs. @gewarren I wonder if this is a known customer concern we may want to address in the future?

**Comment by gewarren** [comment] 2022-02-09 20:06
This is the first time I've seen such feedback. I do see that the `OperationCanceledException` is documented on [Task.Wait(CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.wait?view=net-6.0#system-threading-tasks-task-wait(system-threading-cancellationtoken)), but as you pointed out, that's not that helpful in this case.

It's probably worth morphing this issue into a more generic issue about `*Async` methods throwing `OperationCanceledException` and leaving the issue open. The [wiki guidance](https://github.com/dotnet/dotnet-api-docs/wiki/Exceptions#guidelines) says:

Ideally, document all exceptions that could surface to the programmer for a given member. For example, if an exception for a method is thrown three levels deep, it still appears to the user as if the method throws it, so you should document it for the method (as well as for the member that directly throws it, if that member is public). However, documenting at this level of detail is a difficult and time-consuming task. For that reason, document all exceptions thrown directly by a member, and do the best you can in looking at nested member calls. Ask PM, Dev, and Test which exceptions users are most likely to encounter, and be sure to document at least those.

**Comment by stephentoub** [comment] 2022-02-09 20:13
> It's probably worth morphing this issue into a more generic issue about *Async methods throwing OperationCanceledException

It's even more general than that, not limited to OperationCanceledException.  The issue is that, with async methods, and more generally Task-returning methods, the majority of exceptions don't emerge synchronously from the call.  Rather, any exception gets stored into the returned Task, and then later asking that Task for the exception (via await'ing it, .Wait()'ing it, accessing its .Exception), etc., will surface the exception.  If you have a method:
```C#
public static async Task MethodAsync()
{
    await Task.Yield();
    throw new FormatException();
}
```
and you call it as:
```C#
Task t = MethodAsync();
```
the call to MethodAsync will never throw a `FormatException`.  Rather, such an exception may emerge when you later await the task, e.g.
```C#
await t; // throws FormatException
t.GetResult().GetAwaiter(); // throws FormatException
t.Wait(); // throws an AggregateException wrapping FormatException
Exception e = Task.Exception; // returns an AggregateException wrapping FormatException
...
```
Historically, then, we haven't documented FormatException as an exception thrown out of MethodAsync, because technically it's not.  Of course, in the 95% use case where a developer does:
```C#
await MethodAsync();
```
the distinction is irrelevant, as it's not directly observable whether the exception was thrown from MethodAsync or by awaiting the task it returned.

**Comment by ericstj** [comment] 2022-03-11 21:24
@stephentoub based on your response I believe the recommendation is to not add `OperationCanceledException` as a documented exception to every cancellable API in the framework, so I will close this since I think the initial question was answered.

**Closed by ericstj** 2022-03-11 21:24 UTC
Labels: Pri3, area-Meta, :watch: Not Triaged

**Comment by stephentoub** [comment] 2022-03-11 21:32
> based on your response I believe the recommendation is to not add OperationCanceledException as a documented exception to every cancellable API in the framework, so I will close this since I think the initial question was answered.

To clarify, given a method like:
```C#
Task SomeLibraryMethodAsync(CancellationToken cancellationToken);
```
we would consider it an implementation bug if you were to do:
```C#
Task t;
try
{
    t = SomeLibraryMethodAsync(token);
}
catch (OperationCanceledException)
{
    Debug.Fail("This should never happen");
}
```
and that assert were to ever trip.  The cancellation exception, as with most any exception type other than argument validation exceptions, shouldn't emerge from such asynchronous methods synchronously... rather, the exceptions should be stored into the returned task.  It wouldn't be until you awaited that task:
```C#
try
{
     await t;
}
catch (OperationCanceledException)
{
    // This is perfectly expected as a possibility
}
```
that the exception would propagate from the await.

So we shouldn't add OperationCanceledException to most of any our methods if adding it means the exception might propagate out synchronously.  And we currently lack a story for documenting what exceptions are expected to be stored into the returned Task.  Addressing that latter issue is the more important issue here.

**Comment by gewarren** [comment] 2022-03-17 00:20
Should we open a new issue to discuss documenting exceptions that are stored in tasks by Task-returning methods?

One idea is to use a new XML tag in the /// comments, separate to `[<exception>](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#exception)`. And then for docs, we could translate that new tag into [an additional section](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.comparer-1.compare?view=net-6.0#exceptions) in the docs, something like "Stored Exceptions".
