### ISSUE TITLE
NumberDecimalSeparator tooltip wrong (in french)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/dotnet-api-docs#6765] opened 2021-05-25 14:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NumberDecimalSeparator-tooltip-wrong-in/1386467)._

---
[severity:Other]
Hi,

When hovering on NumberDecimalSeparator in my code `formatInfo.NumberDecimalSeparator` (formatInfo being of the type NumberFormatInfo) with the french version of Visual Studio, the tooltip say " La valeur par défaut de NumberFormatInfo.InvariantInfo est «+». ".
It's displaying the wrong symbol at the end, possible symbols here at '.' or ',' but '+' is obviously wrong, this is worth investigating.

---
#### Feedback Bot on 4/1/2021, 11:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ManickaP** [comment] 2021-05-25 14:29
The problem is with French translation https://docs.microsoft.com/fr-fr/dotnet/api/system.globalization.numberformatinfo.numberdecimalseparator?view=net-5.0, I'm sorry if this should have been transferred to a different repo.

**Comment by tannergooding** [comment] 2021-05-25 14:37
@carlossanlop, where are the translated variants and what's the appropriate way to fix this?

**Comment by gewarren** [comment] 2021-05-25 18:35
Here's the source for that - https://github.com/dotnet/dotnet-api-docs.fr-fr/blob/ca772db1c930f2487ec64c552a67d5cbd8fabb8a/xml/System.Globalization/NumberFormatInfo.xml#L1710. Adding @JasonCard for comment too.

**Comment by JasonCard** [comment] 2021-06-01 20:37
This is machine translation issue, so I'll follow up to uplift this topic to human translation to resolve and update.

**Comment by JasonCard** [comment] 2021-06-03 21:34
Hello @pgovind , 
 
Thank you for your contribution!  Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding Microsoft team and will close this one.
 
Kind regards,
Microsoft DOCS Global Experience Team

**Closed by JasonCard** 2021-06-03 21:34 UTC
Labels: :watch: Not Triaged, Pri3
