### ISSUE TITLE
Class name in api reference not displayed

### ISSUE THREAD

**Issue by IvenBach** [dotnet/dotnet-api-docs#4431] opened 2020-06-23 23:36 UTC
When searching for a class name via https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7 when a class name should appear as part of the Description column it is not shown.
 - As shown in link above for Accessibility Namespace: "The namespace and all of ..."
 - As shown in [Accessibility Namespace](https://docs.microsoft.com/en-us/dotnet/api/accessibility?view=netframework-4.7) description: "The [Accessibility](https://docs.microsoft.com/en-us/dotnet/api/accessibility?view=netframework-4.7) namespace and all of ..."

The above are easy to miss. The examples below are blatantly obvious.

Searching for https://docs.microsoft.com/en-us/dotnet/api/?view=netframework-4.7&term=tree.
 - [System.Windows.Forms.TreeNode](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treenode?view=netframework-4.7)'s description: "Represents a node of a ." ***Note:*** space before the period.
 - [System.Windows.Forms.TreeViewEventArgs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.treevieweventargs?view=netframework-4.7): "Provides data for the , , , or events of a control."

**Comment by mairaw** [comment] 2020-06-30 06:35
Thanks @IvenBach. We're aware of this issue and it's been on the engineering backlog for a while now. 

Duplicate of https://github.com/MicrosoftDocs/feedback/issues/637

**Closed by mairaw** 2020-06-30 06:35 UTC
Labels: :watch: Not Triaged
