### ISSUE TITLE
ImmutableArray<T>.Slice() method doesn't exist

### ISSUE THREAD

**Issue by NWoodsman** [dotnet/dotnet-api-docs#10051] opened 2024-06-22 21:05 UTC
The documentation for .Net6 [here](https://learn.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablearray-1.slice?view=net-6.0#system-collections-immutable-immutablearray-1-slice(system-int32-system-int32)) suggests that a `.Slice()` method exists, however I cannot find it in .Net 6. 

It appears that the method is implemented as part of `System.Collections.Immutable v8.0.0`.

**Comment by gewarren** [comment] 2024-10-19 00:20
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is they the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of #10012.

**Closed by gewarren** 2024-10-19 00:20 UTC
Labels: untriaged, Pri3, area-System.Collections
