### ISSUE TITLE
Formatting for "o" is incorrect

### ISSUE THREAD

**Issue by adamgoon** [dotnet/dotnet-api-docs#1895] opened 2019-02-19 20:04 UTC
.ToString("o") format returns "2008-06-15T21:15:07.0000000+00:00" not "2008-06-15T21:15:07.0000000" as stated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e0b6ca-7464-78b3-0f9f-3d404d18b8c0
* Version Independent ID: 8338c51d-b558-b442-322c-3d056b62194f
* Content: [DateTime.ToString Method (System)](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tostring?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.DateTime.ToString);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System/DateTime.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/DateTime.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment] 2019-02-19 22:31
Thanks for your feedback, @adamgoon. However, I can't reproduce this behavior from the existing sample. 

According to the documentation on [standard format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier), the "o" format specifier displays the output shown in the example if used with a DateTime value whose Kind is DateTimeKind.Unspecified. The output you're displaying is produced by the "o' format string with either a DateTimeOffset value or a DateTime value whose Kind property is DateTimeKind.Local. Moreover, this behavior is consistent on .NET Framework and .NET Core.

I'll close this issue as Not Repro.

**Closed** 2019-04-05 17:24 UTC
Labels: Source - Docs.ms, not-repro
