### ISSUE TITLE
Link of DataView Filter expression sample is using external website

### ISSUE THREAD

**Issue by eriawan** [dotnet/dotnet-api-docs#1961] opened 2019-02-26 10:17 UTC
On this page about DataTable.Select: 
https://docs.microsoft.com/en-us/dotnet/api/system.data.datatable.select?view=netframework-4.7.2 

It contains reference link for "filter expression" to external website: 
https://www.csharp-examples.net/dataview-rowfilter/

![image](https://user-images.githubusercontent.com/8773147/53405329-31137500-39ea-11e9-908a-6190a52b69d9.png)

I have been trying to search for specific documentation on the docs itself, I could not find a guidance on "filter expression".  Why don't MS Docs of .NET Framework API have its own doc page for this?

While this external source link may be ok for others, for me it's not ok at all. Because having dependencies to external website about crucial documentation and samples of .NET APIs itself can't guarantee the validity of the external sources, especially if the external sources went down for any reason (e.g. expired domain name).

Please have written docs on this, and avoid depending on external website.

**Comment by eriawan** [comment] 2019-02-28 04:45
@mairaw ,

Pardon, any update on this issue? Or do I have to tag someone else about this?

**Comment by eriawan** [comment] 2019-03-12 04:14
@mairaw 

please confirm, is there any update on this issue?
I would like to propose new page for the article that has Filter expression sample.

**Comment by mairaw** [comment] 2019-03-12 04:54
Hi @eriawan, thanks for your feedback and sorry for the delay on triaging the issues here. 

I'll be closing this issue here as a duplicate of https://github.com/dotnet/docs/issues/3905. Let's continue the discussion there. I'd have to involve the writer of the data content on that issue.

**Closed by mairaw** 2019-03-12 04:54 UTC
Labels: :watch: Not Triaged
