### ISSUE TITLE
Wrong "Applies to" version information for JsonSerializerOptions.Web property

### ISSUE THREAD

**Issue by cremor** [dotnet/dotnet-api-docs#10588] opened 2024-10-18 05:50 UTC
### Type of issue

Other (describe below)

### Description

The "Applies to" section of that page currently lists .NET 8+, .NET Framework 4.6.2+ and .NET Standard 2.0. This is wrong, the property is new in .NET 9.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.web?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text.Json/JsonSerializerOptions.xml

### Document Version Independent Id

24b463f8-8ffd-f870-480a-0d372f3ad22a

### Article author

@dotnet-bot

**Comment by gewarren** [comment] 2024-10-19 00:31
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is why the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:31 UTC
Labels: untriaged, Pri3, area-System.Text.Json
