### ISSUE TITLE
xvalue

### ISSUE THREAD

**Issue by simen68** [dotnet/dotnet-api-docs#10348] opened 2024-09-02 14:21 UTC
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datavisualization.charting.series.xvaluemember?view=netframework-4.8&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Forms.DataVisualization.Charting.Series.XValueMember)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.8)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows.Forms.DataVisualization.Charting/Series.xml

### Document Version Independent Id

d033e2dc-9681-58a2-5841-7c2c0e3dbd6e

### Article author

@dotnet-bot

**Comment by krwq** [comment] 2024-09-05 11:09
I'll close this as a duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10349 - please clarify what changes are you expecting

**Closed by krwq** 2024-09-05 11:09 UTC
Labels: untriaged, Pri3
