### ISSUE TITLE
JsonElement.DeepEquals should not be marked as available in .NET 8

### ISSUE THREAD

**Issue by madmox** [dotnet/dotnet-api-docs#10336] opened 2024-08-29 10:27 UTC
### Type of issue

Other (describe below)

### Description

The documentation is misleading because this method is not available in .NET 8. It is only available since v9.0.0-preview.6.24327.7 (.NET 9 preview 6).

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.deepequals?view=net-8.0&viewFallbackFrom=net-6.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text.Json/JsonElement.xml

### Document Version Independent Id

0bb893c8-d221-ae85-4b64-3f8df601f976

### Article author

@dotnet-bot

**Comment by vcsjones** [comment] 2024-09-05 14:32
`System.Text.Json` is a NuGet package. You can use the `v9.0.0-preview.6.24327.7` package in .NET 8. That is why the API is also marked as available in .NET Standard and .NET Framework.

**Comment by madmox** [comment] 2024-09-05 15:17
It is very confusing because `System.Text.Json` is part of the .NET runtime, I have no direct package reference to this nuget. The .NET 8 runtime currently uses `System.Text.Json` 8, so the documentation doesn't reflect what API is currently available in a .NET 8 solution by default.

**Comment by gewarren** [comment] 2024-10-19 00:28
Thanks for the feedback. We've received a lot of feedback like this that the current info is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:28 UTC
Labels: untriaged, Pri3, needs-area-label
