### ISSUE TITLE
Translated method names in index of page showing mix of translated/untranslated content

### ISSUE THREAD

**Issue by PuzzleBlue** [dotnet/dotnet-api-docs#10589] opened 2024-10-18 08:48 UTC
### Type of issue

Other (describe below)

### Description

The page content was in english. I don't know if this is normal. I expected it to be in french.
However, in the Index panel, the items for the Window use translated names: 

- The class name `Window ` was replaced with the translation Fenêtre 
- The item for method `Activate` shows up as `Activer`
- The item for method `Close ` shows up as `Fermer`

![Image](https://github.com/user-attachments/assets/f2dbf821-49eb-43f2-879c-5931804368e9)

### Page URL

https://learn.microsoft.com/fr-fr/dotnet/api/system.windows.window.-ctor?view=windowsdesktop-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Windows/Window.xml

### Document Version Independent Id

9d53461c-e7fe-e93b-7862-256188c40a8b

### Article author

@dotnet-bot

**Comment by gewarren** [comment] 2024-10-19 00:15
Thank you. This is a known issue and I hope it gets fixed soon. Closing as duplicate of #8814.

**Closed by gewarren** 2024-10-19 00:15 UTC
Labels: area-WPF, untriaged, Pri3
