### ISSUE TITLE
String Split Documentation no correct for Xamarin Android 

### ISSUE THREAD

**Issue by michaelbayles** [dotnet/dotnet-api-docs#1981] opened 2019-03-02 16:50 UTC
# String Split Documentation

Upon upgrading from Visual Studio 2015 to Visual Studio 2017, I had some unit tests fail.
The unit test project was targeting .NET Framework 4.52, and the project under test was targeting Xamarin Android 6.0.
The test failed with the following exception

```csharp
System.MissingMethodException: Method not found: 'System.String[] System.String.Split(Char, System.StringSplitOptions)'.
```

I starting browsing the [String.Split method documentation](https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netframework-4.5.2).
I noticed `Split(char separator, StringSplitOptions options)` was not found in .NET Framework 4.5.2 or Xamarin Android.

However, I am able to use that overload when targeting Xamarin Android (even in Visual Studio 2017).

[Sample Source Code](https://github.com/michaelbayles/StringSplitDocumentation)

**Comment by mairaw** [comment] 2019-03-08 03:58
Yes, that's by design since those APIs really don't exist on those versions. It seems your issue would be duplicate of https://github.com/MicrosoftDocs/feedback/issues/314.

Right now, the best way to see if the API is supported or not on the target you want is to select the desired version and look at the list of overloads. That should be correct.

For this reason, I'm closing this one since we have a tracking issue. But if I misunderstood your feedback, please let me know.

**Closed by mairaw** 2019-03-08 03:58 UTC
Labels: :watch: Not Triaged
