### ISSUE TITLE
Static contructor's C# syntax string is missing `static`

### ISSUE THREAD

**Issue by TianqiZhang** [dotnet/dotnet-api-docs#2529] opened 2019-05-31 06:09 UTC
For example, this constructor:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Runtime.InteropServices.CustomMarshalers/TypeToTypeInfoMarshaler.xml#L39

it's a static one, you can tell from its name (`.cctor`) or IL. However its C# syntax does not show `static`.

**Comment by rpetrusha** [comment] 2019-06-03 22:36
I don't think that the problem here is that `static` is missing, @TianqiZhang; the problem is that it appears as a public method. Unless static constructors in .NET Framework 1.0/1.1 were different than in .NET Framework 2.0 and later (and I don't think that they were), static constructors are never public and are not directly callable. So they shouldn't appear in the documentation at all.

**Comment by rpetrusha** [comment] 2019-06-04 15:46
This is in fact a public static class constructor in .NET Fremework 1.1. #2536 changes the C# and VB syntax so that it is correct.

**Comment by mairaw** [comment] 2019-06-04 19:49
Closing this as external since this is an mdoc issue. Bug filed in DevOps:
https://ceapex.visualstudio.com/Engineering/_workitems/edit/97094

**Closed by mairaw** 2019-06-04 19:49 UTC
