### ISSUE TITLE
DirectoryInfo.SetAccessControl API not available in 3.0, even though it exists

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3372] opened 2019-10-18 16:59 UTC
If you try to go to this page: https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.setaccesscontrol?view=netcore-3.0

You get redirected to the .NET Framework 4.8 version, even though the API exists in 3.0.

Here's the API in CoreFX, it's public: https://github.com/dotnet/corefx/blob/226f57b4f2bf91822604aa73338070c601d7a0fe/src/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.cs#L23

I think this is a bug in Docs, @mairaw. Maybe a problem with mdoc when reflecting on the ref assemblies?

**Comment by carlossanlop** [comment] 2019-12-05 23:50
@safern did you get a chance to look into this? Do you know if this API is included in the reference assemblies we pass to the Docs team?

**Comment by safern** [comment] 2019-12-23 19:59
I looked at this and the reason why it is not shown for .NET Core is because this API was not ported directly as part of `DirectoryInfo`, it was added as an extension method.

https://apisof.net/catalog/System.IO.FileSystemAclExtensions.SetAccessControl(DirectoryInfo,DirectorySecurity)

https://github.com/dotnet/corefx/blob/release/3.0/src/System.IO.FileSystem.AccessControl/ref/System.IO.FileSystem.AccessControl.cs#L17

**Comment by mairaw** [comment] 2019-12-23 20:26
So I'll close this by design.

**Closed by mairaw** 2019-12-23 20:26 UTC
Labels: P1, doc-bug, external
