### ISSUE TITLE
Docs are unclear about versioning

### ISSUE THREAD

**Issue by davesmits** [dotnet/dotnet-api-docs#10111] opened 2024-07-15 07:14 UTC
This page:
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.addlink?view=net-8.0

states that there is a AddLink method already available in .net 8.

But seems this method is added in .net 9:
https://github.com/dotnet/runtime/issues/97680

please make sure the docs are more clear what is available in what specific version

**Comment by tarekgh** [comment] 2024-07-23 22:06
@davesmits the new releases of the library can run on the previously supported platforms. So, the added API is supported on .NET 8.0 too. The current doc list 8, 9 which is correct. 

CC @gewarren

**Comment by gewarren** [comment] 2024-07-23 23:39
I've seen a number of reports that this is confusing. There is a design change planned that will make this clearer (it will say "package-provided" for APIs that are available through packages only for a given version). I'll close this as a dupe of #10012.

**Closed by gewarren** 2024-07-23 23:39 UTC
Labels: Pri3, area-Infrastructure
