### ISSUE TITLE
Method names are translated in menu

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/dotnet-api-docs#9655] opened 2024-02-28 17:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Method-names-are-translated-in-menu/10582201)._

---
https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.interlocked.increment?view=net-7.0

![image](https://github.com/dotnet/dotnet-api-docs/assets/45579687/0ec01524-2bda-4c83-9013-96881c44ca0a)

Estimated behaviour: Method names written in english always, independent of content language.

---
#### Feedback Bot on 2/11/2024, 01:44 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by gewarren** [comment] 2024-03-20 21:49
[Internal work item](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/910837)

**Comment by gewarren** [comment] 2024-05-16 18:07
Related to #9774, #8814.

**Comment by gewarren** [comment] 2024-10-19 00:16
Thank you. This is a known issue and I hope it gets fixed soon. Closing as duplicate of #8814.

**Closed by gewarren** 2024-10-19 00:16 UTC
Labels: loc, untriaged, Pri3, area-System.Threading
