### ISSUE TITLE
List.Sort() example should include Duplicate values

### ISSUE THREAD

**Issue by MightyPen** [dotnet/dotnet-api-docs#1874] opened 2019-02-17 09:48 UTC
For the C# code example in the method overload 'Sort()', the name "Jody" should have two occurrences in the initial string[] array (not just one), anywhere not next to each other.
Then the two Jody's should appear together in the second line of output (the sorted output).
REASON: StackOverflow website has lots of .NET users asking for options on how to have something roughly like a SortedList that retains Duplicate keys.  List.Sort() is one important option, but this option is semi-hidden in the current documentation.
Thank you.
GeneMi at Msft , 2019/02/17 
@MightyPen 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36bdb60d-fa8f-84c1-6d7d-e17b06096112
* Version Independent ID: 1dc86b79-6cc3-b1ed-dd07-99559381a82c
* Content: [List&lt;T&gt;.Sort Method (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.sort?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/List`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/List`1.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment] 2019-04-05 23:27
Duplicate of #1875

**Closed by mairaw** 2019-04-05 23:27 UTC
Labels: :watch: Not Triaged, Source - Docs.ms
