### ISSUE TITLE
Double.IsFinite(Double) Method not in System namespace in recent .Net framework

### ISSUE THREAD

**Issue by kathleenwest** [dotnet/dotnet-api-docs#2254] opened 2019-04-04 22:23 UTC
dotnet-api-docs/xml/System/Double.xml
https://docs.microsoft.com/en-us/dotnet/api/system.double.isfinite?view=netstandard-2.1

The method Double.IsFinite(Double) is not showing up in the System namespace. Verify this in Visual Studio and other places. Was it removed from the most recent .Net framework version?

**Comment by tannergooding** [comment] 2019-04-04 22:36
What framework version are you targeting?

`double.IsFinite(double)` is only available in .NET Core 2.1+ and will also be available in .NET Standard 2.1+.

**Comment by mairaw** [comment] 2019-04-04 22:51
This is not supported in the .NET Framework @kathleenwest. The applicable versions are listed in the bottom: https://docs.microsoft.com/en-us/dotnet/api/system.double.isfinite?view=netstandard-2.1#applies-to

So I'm closing this as by design but please let me know if I missed anything.

**Closed by mairaw** 2019-04-04 22:51 UTC
Labels: :watch: Not Triaged

**Comment by kathleenwest** [comment] 2019-04-06 23:57
I really wish this was supported in the .Net Framework as I needed to utilize the method.

**Comment by tannergooding** [comment] 2019-04-07 00:43
The implementation can be found here: https://source.dot.net/#System.Private.CoreLib/shared/System/Double.cs,02ee32eb42d32941

It is fairly trivial and MIT licensed if having your own internal helper is suitable.

**Comment by kathleenwest** [comment] 2019-04-09 01:00
Thanks for the code link @tannergooding
