### ISSUE TITLE
Metrics instrument of type Guage<> not available in .NET 8

### ISSUE THREAD

**Issue by melwynpkb** [dotnet/dotnet-api-docs#10380] opened 2024-09-10 01:14 UTC
### Type of issue

Other (describe below)

### Description

Guage<> is not supported in .NET 8 but the documentation seems to indicate it does. 
See .NET 8 and .NET 9 branches below
https://github.com/dotnet/runtime/tree/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.gauge-1?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Diagnostics.Metrics/Gauge`1.xml

### Document Version Independent Id

40be00e4-b2c4-2443-541c-dc6838a74666

### Article author

@dotnet-bot

**Comment by divyeshio** [comment] 2024-09-14 01:47
Not only Gauge<> but other types in the namespace like MeterOptions, IMeterFactory that are unavailable below .net 8 are also showing up as available in .net 6 and 7. But xml files are fine, I think there's some issue with doc page generation?

**Comment by gewarren** [comment] 2024-10-19 00:29
Thank you for the feedback. The NuGet package is compatible with down-level versions, which is they the older versions are shown in the Applies to table. But we've also received a lot of feedback that this is too confusing. We have a design change in the works to hopefully make this less confusing. Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012.

**Closed by gewarren** 2024-10-19 00:29 UTC
Labels: untriaged, Pri3, area-System.Diagnostics
