### ISSUE TITLE
FrozenDictionary<TKey,TValue> documentation: lists support for .NET 6 and .NET 7 but it was first available in .NET 8

### ISSUE THREAD

**Issue by udlose** [dotnet/dotnet-api-docs#10591] opened 2024-10-18 15:49 UTC
### Describe the issue or suggestion

Per [FrozenDictionary<TKey,TValue> Class - Applies To section](https://learn.microsoft.com/en-us/dotnet/api/system.collections.frozen.frozendictionary-2?view=net-6.0&devlangs=csharp#applies-to), the versions listed that have FrozenDictionary are listed as .NET 6, 7, 8, 9.

FrozenDictionary does not exist in .NET 6 or .NET 7.  Please update the docs.

![Image](https://github.com/user-attachments/assets/8d72bd42-3677-4373-b01b-cdbe2c968be9)

**Comment by eiriktsarpalis** [comment] 2024-10-18 16:16
FYI @gewarren @BillWagner. We seen to be getting multiple customer reports about this being an issue.

**Comment by gewarren** [comment] 2024-10-18 16:59
@eiriktsarpalis This is definitely a problem and confusing for customers (I see lots of feedback about this through the "black box" UUF feedback channel as well). We previously had completely separate ".NET platform extensions" monikers that we removed in favor of showing the .NET versions that the down-level packages are compatible with. We did that in part because that's how [apisof.net](https://apisof.net/catalog/83265d86ab93662b404c54d5d86d90aa) shows the applicable versions:

![Image](https://github.com/user-attachments/assets/0d924361-375c-4456-a377-0cf54481f310)

The problem for the API reference docs on learn.microsoft.com is that the Applies to table doesn't differentiate between package-provided and in-box versions. If we were to split out the Applies to table like this mock-up from an [internal work item](https://dev.azure.com/ceapex/Engineering/_workitems/edit/970004), would that help? Or do you have any other ideas on how to resolve this?

![Image](https://github.com/user-attachments/assets/cb3cfe40-f51a-488b-b644-579e75a47a18)

cc @nickwalkmsft

**Comment by gewarren** [comment] 2024-10-19 00:32
I'm going to close this as a duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10012. Please leave any further feedback or ideas there.

**Closed by gewarren** 2024-10-19 00:32 UTC
Labels: untriaged, Pri3, area-System.Collections
