### ISSUE TITLE
Mamata oli

### ISSUE THREAD

**Issue by Mamata2003** [dotnet/dotnet-api-docs#10556] opened 2024-10-13 06:13 UTC
### Type of issue

Typo

### Description

[Enter feedback here]

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.runtime.versioning.requirespreviewfeaturesattribute?view=net-8.0

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Runtime.Versioning/RequiresPreviewFeaturesAttribute.xml

### Document Version Independent Id

f80e0594-9ba4-9fcf-1887-7b4e03ccb106

### Article author

@dotnet-bot

**Comment by steveharter** [comment] 2024-10-14 15:22
@Mamata2003 please provide the actual typo; I couldn't find one.

**Comment by steveharter** [comment] 2024-10-14 15:24
Closing as duplicate of https://github.com/dotnet/dotnet-api-docs/issues/10555

**Closed** 2024-10-14 15:24 UTC
Labels: needs-author-action, untriaged, Pri3, area-System.Runtime
